# Generated by Django 4.0.3 on 2022-08-11 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ref_no', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('catalogue', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published', models.CharField(max_length=4)),
                ('publisher', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=60)),
                ('image', models.ImageField(default='icon.png', upload_to='Books/')),
                ('rating', models.CharField(max_length=3)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('ref_no', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
                ('returned', models.BooleanField(default=False, editable=False)),
                ('total_books', models.PositiveIntegerField(default=0, editable=False)),
                ('fine', models.PositiveIntegerField(default=0, editable=False)),
                ('borrowed', models.DateTimeField(auto_now_add=True)),
                ('date_returned', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('dp', models.ImageField(default='default.png', upload_to='Dps/')),
                ('gender', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=14)),
                ('library', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('lib', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lib'],
            },
        ),
    ]
