# Generated by Django 4.0.3 on 2022-05-14 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_ref_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=150)),
                ('year_of_publication', models.CharField(max_length=4)),
                ('type_of_book', models.CharField(max_length=50)),
                ('book_photo', models.ImageField(upload_to='')),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.UUIDField(default=uuid.UUID('b51d559b-c54a-4a8b-8486-4d55188da565'), editable=False)),
                ('stud_name', models.CharField(max_length=150)),
                ('stud_mobile_no', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('book_ref_no', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=150)),
                ('year_of_publication', models.CharField(max_length=4)),
                ('type_of_book', models.CharField(max_length=50)),
                ('book_photo', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('fine', models.FloatField(blank=True, default=0, null=True)),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('date_returned', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9f4b9edd-baa4-4608-b96c-7ce327f619ec'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=6)),
                ('lib_mobile_no', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(default='male.png', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lib', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
