# Generated by Django 4.0.3 on 2022-05-14 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staffaccounts', '0002_alter_librarian_id_alter_student_stud_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='librarian',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8b6100c-e1c6-4fda-afab-cc5196738f9d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.UUIDField(default=uuid.UUID('0dc20316-317e-48f0-a9f4-fae908c2af2f'), editable=False),
        ),
    ]
