# Generated by Django 4.0.3 on 2022-05-14 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staffaccounts', '0003_remove_books_quantity_remove_student_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d41c4245-ae35-48a3-8666-917b16a118b0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.UUIDField(default=uuid.UUID('8f5cfda1-42ce-47ad-bc32-8b653f08118e'), editable=False),
        ),
    ]
